apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "envoy-oauth2-middleware.fullname" . }}
  labels:
    {{- include "envoy-oauth2-middleware.labels" . | nindent 4 }}
stringData:
  envoy.yaml: |
    {{- include "envoy-oauth2-middleware.config" . | nindent 4 }}